### ISSUE TITLE
destructor check for children gives a warning

### ISSUE THREAD

**Issue by astortz** [stevan/tree-simple#8]
In Simple.pm, in the destructor:

    unless (!$self->{_children} && scalar(@{$self->{_children}}) == 0) {
        foreach my $child (@{$self->{_children}}) {
            defined $child && $child->_detachParent();
        }
    }

the '&&' in the first line should most likely be an '||'.  I discovered this when I got this warning from perl:

Can't use an undefined value as an ARRAY reference at ..../lib64/site_perl/Tree/Simple.pm line 574.

The !$self->{_children} check was undoubtedly meant to short-circuit this warning, but doesn't in its current form.

**Comment by ronsavage** [comment]
Thanx for the report.

I changed line 574 to be, simply:
    if ($self->{_children}) {
since the other test in that file is performed anyway by the for loop, and if the # of children is 0, it immediately drops out of the look.

See if that helps. I'm sure it will.

V 1.25 is now on CPAN.

**Comment by astortz** [comment]
That's great, I appreciate the quick turnaround!
